
/// <summary>
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
/// By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
/// find the sum of the even-valued terms.
/// </summary>

public class Problem2
{
    public long FibonacciEvenSum()
    {
        long a = 1;
        long b = 2;
        long c = 0;
        long sumOfEven = b;

        while(c < 4_000_000)
        {
            c = a + b;
            a = b;
            b = c;

            if (c % 2 == 0)
                sumOfEven += c;
        }

        return sumOfEven;
    }
}
